// Codex custom agents for the workit roles, rendered from the canonical Claude
// Code agent definitions (packages/workit-claude-code/agents/*.md).
//
// codex-cli 0.160.1 has no plugin agents: a plugin bundles skills, MCP
// servers, apps and hooks (developers.openai.com/codex/plugins/build; the
// app-server PluginDetail schema from `codex app-server generate-json-schema`
// has no agents field), and an `agents/` dir inside an installed plugin is not
// read. Custom agents are standalone TOML files under `$CODEX_HOME/agents/`
// (personal) or `.codex/agents/` (project), each defining `name`,
// `description` and `developer_instructions`, plus optional config keys such
// as `sandbox_mode` (learn.chatgpt.com/docs/agent-configuration/subagents).
// So the plugin ships the files and its MCP launcher copies them into
// `$CODEX_HOME/agents/` (installCodexAgents); Codex reads them at session start.
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";

export const CODEX_AGENT_ROLES = ["verifier", "reviewer", "implementer"] as const;
export type CodexAgentRole = (typeof CODEX_AGENT_ROLES)[number];

/** First line of every generated agent file: marks a file workit may refresh. */
export const CODEX_AGENT_MARKER = "# Generated by Workit";

/** The Codex agent name: the SubagentStart hook keys roles on `workit-<role>`. */
const codexAgentName = (role: CodexAgentRole): string => `workit-${role}`;
export const codexAgentFile = (role: CodexAgentRole): string => `${codexAgentName(role)}.toml`;

// Judges never edit: Codex enforces it with a read-only sandbox (the Claude
// agents drop the Write/Edit tools instead). The implementer inherits the
// lead's sandbox because it edits and commits in its own worktree.
const SANDBOX: Record<CodexAgentRole, string | null> = {
  verifier: "read-only",
  reviewer: "read-only",
  implementer: null,
};

const JUDGE_SANDBOX_NOTE =
  "Codex runs you in a read-only sandbox. `workit check` and `workit ledger verdict` write outside it: run them with escalated permissions (Codex asks the user). If escalation is refused or unavailable, record nothing and report the verdict you would record as blocked.";

const IMPLEMENTER_WORKTREE_NOTE =
  "Codex does not isolate subagents: the lead creates your worktree with `workit fanout worktree create <slice>` and names it in the brief. Work only there, never in the lead's checkout.";

const parseAgentMarkdown = (text: string) => {
  const match = /^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/.exec(text);
  if (!match) throw new Error("agent definition has no frontmatter");
  const field = (name: string) =>
    new RegExp(`^${name}:\\s*(.+)$`, "m").exec(match[1])?.[1].trim() ?? "";
  return { description: field("description"), body: match[2].trim() };
};

/** Claude Code wording in the canonical body, in Codex terms. */
const toCodexText = (body: string): string =>
  body
    .replace(/\(`\/workit:([a-z-]+)`\)/g, "(`$workit-$1`)")
    .replace(/`\/workit:([a-z-]+)`/g, "`$workit-$1`")
    .replace("a branch name chosen by Claude Code", "a branch name you did not choose");

const tomlString = (value: string): string => JSON.stringify(value);

const tomlLiteralBlock = (value: string): string => {
  if (value.includes("'''")) throw new Error("agent text cannot contain '''");
  // Text starts on the opening line: TOML trims a newline right after ''',
  // but not every parser does (Bun.TOML keeps it).
  return `'''${value}\n'''`;
};

/** One Codex agent TOML file rendered from the canonical Claude agent. */
const renderCodexAgent = (
  role: CodexAgentRole,
  canonicalMarkdown: string,
  source: string,
): string => {
  const { description, body } = parseAgentMarkdown(canonicalMarkdown);
  const note = SANDBOX[role] ? JUDGE_SANDBOX_NOTE : IMPLEMENTER_WORKTREE_NOTE;
  const instructions = `${toCodexText(body)}\n\n${note}`;
  const sandbox = SANDBOX[role];
  return [
    `${CODEX_AGENT_MARKER} from ${source}; edits are overwritten on the next plugin start.`,
    `name = ${tomlString(codexAgentName(role))}`,
    `description = ${tomlString(description)}`,
    ...(sandbox ? [`sandbox_mode = ${tomlString(sandbox)}`] : []),
    `developer_instructions = ${tomlLiteralBlock(instructions)}`,
    "",
  ].join("\n");
};

/** Every role rendered from `claudeAgentsDir` (one `<role>.md` per role). */
export const renderCodexAgents = (claudeAgentsDir: string): Map<string, string> =>
  new Map(
    CODEX_AGENT_ROLES.map((role) => [
      codexAgentFile(role),
      renderCodexAgent(
        role,
        readFileSync(path.join(claudeAgentsDir, `${role}.md`), "utf8"),
        `packages/workit-claude-code/agents/${role}.md`,
      ),
    ]),
  );

/**
 * The Codex home that owns a plugin install, or null outside one: Codex
 * installs plugins under `<CODEX_HOME>/plugins/cache/<marketplace>/<plugin>/<version>`
 * (observed with `codex plugin add` on codex-cli 0.160.1), and MCP servers do
 * not inherit CODEX_HOME, so the install path is the witness.
 */
export const codexHomeOfInstall = (pluginRoot: string): string | null => {
  const parts = path.resolve(pluginRoot).split(path.sep);
  const cache = parts.length - 4;
  return cache >= 2 && parts[cache] === "cache" && parts[cache - 1] === "plugins"
    ? parts.slice(0, cache - 1).join(path.sep) || path.sep
    : null;
};

/** The install's Codex home, else CODEX_HOME, else ~/.codex. */
export const codexHomeFor = (pluginRoot: string, env: NodeJS.ProcessEnv): string =>
  codexHomeOfInstall(pluginRoot) ??
  (env.CODEX_HOME || path.join(env.HOME || os.homedir(), ".codex"));

export type AgentInstallResult = {
  file: string;
  action: "installed" | "updated" | "current" | "kept-user-file";
};

/**
 * Copies the plugin's agents into `<codexHome>/agents/`. A missing file is
 * written; a file carrying the Workit marker is refreshed; a same-named file
 * without the marker belongs to the user and is never overwritten.
 */
export const installCodexAgents = (pluginRoot: string, codexHome: string): AgentInstallResult[] => {
  const source = path.join(pluginRoot, "agents");
  if (!existsSync(source)) return [];
  const target = path.join(codexHome, "agents");
  const results: AgentInstallResult[] = [];
  for (const file of readdirSync(source)
    .filter((name) => name.endsWith(".toml"))
    .toSorted()) {
    const content = readFileSync(path.join(source, file), "utf8");
    const dest = path.join(target, file);
    if (!existsSync(dest)) {
      mkdirSync(target, { recursive: true });
      writeFileSync(dest, content);
      results.push({ file: dest, action: "installed" });
      continue;
    }
    const current = readFileSync(dest, "utf8");
    if (current === content) results.push({ file: dest, action: "current" });
    else if (!current.startsWith(CODEX_AGENT_MARKER))
      results.push({ file: dest, action: "kept-user-file" });
    else {
      writeFileSync(dest, content);
      results.push({ file: dest, action: "updated" });
    }
  }
  return results;
};
