import { expect, test } from "bun:test";
import { spawnSync } from "node:child_process";
import path from "node:path";
import {
  WORKIT_SKILL_ALIASES,
  cursorCommandText,
  renderSkillText,
  skillDescription,
} from "@/packages/workit-core/src/core/skill-manifests";

// Cursor discovers the plugin from git, so its skills/ and commands/ are
// generated by `bun packages/workit-cursor/scripts/build.ts --skills-only` and
// committed. Every other host copy is git-ignored and built at pack time.
// `bun run build` regenerates the copies in place, so comparing working-tree
// files after a build would pass by construction. Compare committed git trees
// instead: a canonical edit committed without its regenerated copies fails.
const repoRoot = path.resolve(import.meta.dir, "../..");

const GENERATED_COPIES: Record<string, string[]> = {
  "packages/workit-core/templates": ["packages/workit-cli/assets/templates"],
};
const CANONICAL_SKILLS = "packages/workit-core/skills";
const CURSOR_SKILLS = "packages/workit-cursor/skills";

const git = (...args: string[]) => spawnSync("git", args, { cwd: repoRoot, encoding: "utf8" });

const committedTree = (relative: string): string => {
  const result = git("rev-parse", `HEAD:${relative}`);
  if (result.status !== 0) throw new Error(`git rev-parse HEAD:${relative}: ${result.stderr}`);
  return result.stdout.trim();
};

const committedFile = (relative: string): string => {
  const result = git("show", `HEAD:${relative}`);
  if (result.status !== 0) throw new Error(`git show HEAD:${relative}: ${result.stderr}`);
  return result.stdout;
};

const committedFiles = (relative: string): string[] =>
  git("ls-tree", "-r", "--name-only", "HEAD", `${relative}/`)
    .stdout.trim()
    .split("\n")
    .map((file) => path.posix.relative(relative, file))
    .toSorted();

test("committed Cursor skills are the canonical skills rendered for Cursor", () => {
  const regenerate = "run bun packages/workit-cursor/scripts/build.ts --skills-only";
  const files = committedFiles(CANONICAL_SKILLS);
  expect(committedFiles(CURSOR_SKILLS), regenerate).toEqual(files);
  for (const file of files) {
    const canonical = committedFile(`${CANONICAL_SKILLS}/${file}`);
    expect(committedFile(`${CURSOR_SKILLS}/${file}`), `${file}: ${regenerate}`).toBe(
      file.endsWith(".md") ? renderSkillText(canonical, "cursor") : canonical,
    );
  }
});

test("committed template copies match the canonical source they are built from", () => {
  for (const [canonical, copies] of Object.entries(GENERATED_COPIES)) {
    const expected = committedTree(canonical);
    for (const copy of copies)
      expect(
        committedTree(copy),
        `${copy} differs from ${canonical}; run bun packages/workit-cli/scripts/build.ts`,
      ).toBe(expected);
  }
});

test("committed Cursor commands are the ones generated from each skill's description", () => {
  const committed = git("ls-tree", "--name-only", "HEAD", "packages/workit-cursor/commands/")
    .stdout.trim()
    .split("\n")
    .map((file) => path.basename(file))
    .toSorted();
  expect(committed).toEqual(
    Object.keys(WORKIT_SKILL_ALIASES)
      .map((alias) => `${alias}.md`)
      .toSorted(),
  );
  for (const [alias, skill] of Object.entries(WORKIT_SKILL_ALIASES)) {
    const description = skillDescription(
      committedFile(`packages/workit-core/skills/${skill}/SKILL.md`),
    );
    expect(committedFile(`packages/workit-cursor/commands/${alias}.md`), alias).toBe(
      cursorCommandText(alias, skill, description),
    );
  }
});

test("no other host commits a skill copy, and a local build stays ignored", () => {
  const copies = [
    "packages/workit-codex/skills",
    "packages/workit-pi/skills",
    "packages/workit-opencode/assets/skills",
    "packages/workit-claude-code/skills",
  ];
  expect(git("ls-files", ...copies).stdout.trim()).toBe("");
  for (const copy of copies)
    expect(git("check-ignore", "-q", `${copy}/workit-shape/SKILL.md`).status, copy).toBe(0);
});
